apply plugin: 'com.android.application'
import org.gradle.api.attributes.Attribute
//
// build.gradle in TeamCode
//
// Most of the definitions for building your module reside in a common, shared
// file 'build.common.gradle'. Being factored in this way makes it easier to
// integrate updates to the FTC into your code. If you really need to customize
// the build definitions, you can place those customizations in this file, but
// please think carefully as to whether such customizations are really necessary
// before doing so.

// Custom definitions may go here

// Include common definitions from above.
apply from: '../build.common.gradle'
apply from: '../build.dependencies.gradle'

android {
    namespace = 'org.firstinspires.ftc.teamcode'

    packagingOptions {
        jniLibs {
            pickFirsts += ['**/*.so']
        }
        jniLibs.useLegacyPackaging true
    }
}

dependencies {
    implementation project(':FtcRobotController')
}
import org.gradle.api.attributes.Attribute

tasks.register('javadoc', Javadoc) {
    description = "Generates Javadoc for TeamCode"
    group = "documentation"

    source = fileTree(dir: 'src/main/java', include: '**/*.java', exclude: '**/internal/**')
    destinationDir = file("$projectDir/javadoc")

    doFirst {
        def artifactType = Attribute.of('artifactType', String)
        def compileClasspathFiles = project.configurations.named("debugCompileClasspath").get()
                .incoming.artifactView {
            attributes {
                attribute(artifactType, 'jar')
            }
            lenient(true)
        }.files

        classpath = project.objects.fileCollection().from(
                android.getBootClasspath(),
                compileClasspathFiles
        )
    }

    failOnError false
    options.encoding = "UTF-8"
    options.addStringOption('Xdoclint:none', '-quiet')
}